### ISSUE TITLE
Doesn't format smarty syntax inside JS script element

### ISSUE THREAD

**Issue by dillanjwilding** [MaxGiting/atom-language-smarty#11]
I'm having an issue where I have smarty comments and statements inside a html <script type="text/javascript"> tag and the syntax is no longer colored or highlighted correctly. Simple example below. Another thing I'm encountering is mismatched quotes in a comment, again inside a script tag, will highlight the rest of the file's text red.

![screen shot 2017-04-26 at 11 46 07 am](https://cloud.githubusercontent.com/assets/2286922/25446090/086c2e56-2a76-11e7-92ed-5a40433362be.png)
![screen shot 2017-04-27 at 12 07 33 pm](https://cloud.githubusercontent.com/assets/2286922/25495264/2a9b4094-2b42-11e7-8ade-f7b8a35f300d.png)

**Comment by MaxGiting** [comment]
I can replicate the comment error, but do not think there is a way around this in the current Grammar implementation. I translated this grammar from the Sublime Smarty Package which shows the same behaviour.

The quotes issue is a limitation with Atom Grammars I believe. You can see the same behaviour if you set the language to PHP instead of Smarty
